spring.application.name=Zenit-Backend

# Connection data
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format-sql=true

# Email sender
spring.mail.host=smtp.sendgrid.net
spring.mail.port=587
spring.mail.username=apikey
mail.sender.part.one=SG.Wjeqp2ijQCStApskwHN-gA.E0xW
mail.sender.part.two=husxglGa93gr1wgPEbZHuXNSERiZCpiUW1Y-gLA
spring.mail.password=${mail.sender.part.one}${mail.sender.part.two}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000
spring.mail.properties.mail.smtp.ssl.trust=smtp.sendgrid.net

# Groq API data
part.one=gsk_sK1M13tZtTTJsjNeeX
part.two=B3WGdyb3FYjg3Psw5Jk6Nht30FRF7innnW
groq.api.key=${part.one}${part.two}
groq.api.url=https://api.groq.com/openai/v1/chat/completions